name: air_sense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_auth: ^6.5.1
  fl_chart: ^1.2.0

  geolocator: ^13.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # ADDED: Package to automate app launcher icon generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logoc.jpeg


# ADDED: Launcher icons configuration block
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"